# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CalculPointDeFonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sous_fonction_deb', models.IntegerField(default=0)),
                ('nombre_sous_fonction_fin', models.IntegerField(default=0)),
                ('nombre_donnees_elementaires_deb', models.IntegerField(default=0)),
                ('nombre_donnees_elementaires_fin', models.IntegerField(default=0)),
                ('complexite', models.CharField(choices=[('faible', 'faible'), ('moyen', 'moyen'), ('\xe9lev\xe9', '\xe9lev\xe9')], default='moyen', max_length=10)),
                ('nombre_point_de_fonction', models.IntegerField(default=0, verbose_name='nombre de points de fonctions')),
            ],
        ),
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_projet', models.CharField(choices=[('OR', 'organique'), ('SD', 'semi-d\xe9tach\xe9'), ('EM', 'embarqu\xe9')], default='organique', max_length=2)),
                ('type_coefficient', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=2)),
                ('valeur_coefficient', models.DecimalField(decimal_places=3, default=None, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DegreIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degre_integration', models.CharField(choices=[('TB', 'tr\xe8s bas'), ('B', 'bas'), ('M', 'moyen'), ('E', '\xe9lev\xe9'), ('TE', 'tr\xe8s \xe9lev\xe9'), ('TTE', 'tr\xe8s tr\xe8s \xe9lev\xe9')], default='moyen', max_length=100, verbose_name="degr\xe9 d'int\xe9gration")),
                ('coefficient_integration', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstimationCocomo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_projet', models.CharField(choices=[('OR', 'organique'), ('SD', 'semi-d\xe9tach\xe9'), ('EM', 'embarqu\xe9')], default='organique', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='EstimationPointDeFonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facteur_ajustement', models.DecimalField(decimal_places=3, default=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fonction', models.CharField(default=None, max_length=100, verbose_name='nom de la fonction')),
                ('nombre_sous_fonction', models.IntegerField(default=0, verbose_name="nombre de sous-fonctions ('GDR ou SLD')")),
                ('nombre_donnees_elementaires', models.IntegerField(default=0, verbose_name='nombre de donn\xe9es \xe9l\xe9mentaires')),
                ('estimation_point_de_fonction', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webcosting.EstimationPointDeFonction')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageDeProgrammation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_de_programmation', models.CharField(max_length=100, verbose_name='language de programmation')),
                ('ligne_de_code_par_points_de_fonctions', models.IntegerField(verbose_name='ligne de code par points de fonctions')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(default=None, max_length=100, verbose_name='nom du projet')),
                ('date_dernier_enregistrement', models.DateTimeField(auto_now=True, null=True, verbose_name='date du dernier enregistrement')),
            ],
        ),
        migrations.CreateModel(
            name='TailleDuProjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille_du_projet', models.CharField(max_length=30, verbose_name='taille du projet')),
                ('charge_de_travail_par_points_de_fonctions', models.IntegerField(verbose_name='charge de travail en jour homme par points de fonctions')),
            ],
        ),
        migrations.CreateModel(
            name='TypeAttribut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_attribut', models.CharField(default=None, max_length=100, verbose_name="type de l'attribut")),
                ('type_attribut_detail', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name="type d\xe9taill\xe9 de l'attribut")),
            ],
        ),
        migrations.CreateModel(
            name='TypeFonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fonction', models.CharField(choices=[('GDI', 'donn\xe9es internes'), ('GDE', 'donn\xe9es externes'), ('ENT', 'entr\xe9es'), ('SOR', 'sorties'), ('INT', 'interrogation')], default='donn\xe9es internes', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='fonction',
            name='type_fonction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webcosting.TypeFonction'),
        ),
        migrations.AddField(
            model_name='estimationpointdefonction',
            name='language_de_programmation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webcosting.LanguageDeProgrammation'),
        ),
        migrations.AddField(
            model_name='estimationpointdefonction',
            name='projet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webcosting.Projet'),
        ),
        migrations.AddField(
            model_name='estimationpointdefonction',
            name='taille_du_projet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webcosting.TailleDuProjet'),
        ),
        migrations.AddField(
            model_name='estimationcocomo',
            name='projet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webcosting.Projet'),
        ),
        migrations.AddField(
            model_name='degreintegration',
            name='type_attribut',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webcosting.TypeAttribut'),
        ),
        migrations.AddField(
            model_name='calculpointdefonction',
            name='type_fonction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webcosting.TypeFonction'),
        ),
        migrations.AddField(
            model_name='attribut',
            name='degre_integration',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webcosting.DegreIntegration'),
        ),
        migrations.AddField(
            model_name='attribut',
            name='estimation_cocomo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webcosting.EstimationCocomo'),
        ),
        migrations.AddField(
            model_name='attribut',
            name='type_attribut',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webcosting.TypeAttribut'),
        ),
    ]
