# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimationpointdefonction',
            name='facteur_ajustement',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='estimationpointdefonction',
            name='language_de_programmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webcosting.LanguageDeProgrammation'),
        ),
        migrations.AlterField(
            model_name='estimationpointdefonction',
            name='taille_du_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webcosting.TailleDuProjet'),
        ),
    ]
