# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcosting', '0003_auto_20160504_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tailleduprojet',
            old_name='charge_de_travail_par_points_de_fonctions',
            new_name='charge_de_travail',
        ),
    ]
