# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosting', '0004_auto_20160505_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribut',
            name='degre_integration',
        ),
        migrations.RemoveField(
            model_name='attribut',
            name='projet',
        ),
        migrations.RemoveField(
            model_name='attribut',
            name='type_attribut',
        ),
        migrations.AddField(
            model_name='projet',
            name='degres_integration',
            field=models.ManyToManyField(to='webcosting.DegreIntegration'),
        ),
        migrations.DeleteModel(
            name='Attribut',
        ),
    ]
