# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosting', '0007_auto_20160517_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degreintegration',
            name='projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='fiab',
            field=models.DecimalField(blank=True, choices=[(0.75, 'tr\xe8s bas: 0.75')], decimal_places=3, default=None, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='DegreIntegration',
        ),
    ]
