# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosting', '0008_auto_20160518_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficient',
            name='type_projet',
            field=models.CharField(choices=[('organique', 'organique'), ('semi-d\xe9tach\xe9', 'semi-d\xe9tach\xe9'), ('embarqu\xe9', 'embarqu\xe9')], default='organique', max_length=10),
        ),
    ]
