# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcosting', '0009_auto_20160518_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='taille_du_projet',
            new_name='taille_projet',
        ),
    ]
