# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcosting', '0010_auto_20160518_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TailleDuProjet',
            new_name='TailleProjet',
        ),
        migrations.RenameField(
            model_name='tailleprojet',
            old_name='taille_du_projet',
            new_name='taille_projet',
        ),
    ]
