# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosting', '0011_auto_20160518_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='fiab',
            field=models.DecimalField(blank=True, choices=[(0.75, 'tr\xe8s bas: 0.75'), (0.88, 'bas: 0.88'), (1.0, 'moyen: 1.00'), (1.15, '\xe9kev\xe9: 1.15'), (1.4, 'tr\xe8s \xe9lev\xe9: 1.40')], decimal_places=3, default=None, max_digits=5, null=True),
        ),
    ]
