# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosting', '0012_auto_20160518_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='donn',
            field=models.DecimalField(blank=True, choices=[(0.94, 'bas: 0.88'), (1.0, 'moyen: 1.00'), (1.08, '\xe9lev\xe9: 1.15'), (1.16, 'tr\xe8s \xe9lev\xe9: 1.40')], decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='fiab',
            field=models.DecimalField(blank=True, choices=[(0.75, 'tr\xe8s bas: 0.75'), (0.88, 'bas: 0.88'), (1.0, 'moyen: 1.00'), (1.15, '\xe9lev\xe9: 1.15'), (1.4, 'tr\xe8s \xe9lev\xe9: 1.40')], decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
