# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosting', '0013_auto_20160518_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculpointdefonction',
            name='nombre_donnees_elementaires_deb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculpointdefonction',
            name='nombre_donnees_elementaires_fin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculpointdefonction',
            name='nombre_point_de_fonction',
            field=models.PositiveIntegerField(default=0, verbose_name='nombre de points de fonctions'),
        ),
        migrations.AlterField(
            model_name='calculpointdefonction',
            name='nombre_sous_fonction_deb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calculpointdefonction',
            name='nombre_sous_fonction_fin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='valeur_coefficient',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='nombre_donnees_elementaires',
            field=models.PositiveIntegerField(default=0, verbose_name='nombre de donn\xe9es \xe9l\xe9mentaires'),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='nombre_sous_fonction',
            field=models.PositiveIntegerField(default=0, verbose_name="nombre de sous-fonctions ('GDR ou SLD')"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='donn',
            field=models.DecimalField(blank=True, choices=[(0.94, 'bas (0.94)'), (1.0, 'moyen (1.00)'), (1.08, '\xe9lev\xe9 (1.08)'), (1.16, 'tr\xe8s \xe9lev\xe9 (1.16)')], decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='facteur_ajustement',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='tailleprojet',
            name='charge_de_travail',
            field=models.PositiveIntegerField(verbose_name='charge de travail en jour homme par points de fonctions'),
        ),
    ]
