# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosting', '0015_auto_20160519_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficient',
            name='valeur_coefficient',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='projet',
            name='facteur_ajustement',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
