# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcosting', '0017_auto_20160521_0822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeAttribut',
        ),
        migrations.RenameField(
            model_name='languagedeprogrammation',
            old_name='ligne_de_code_par_points_de_fonctions',
            new_name='ligne_de_code',
        ),
        migrations.AlterField(
            model_name='projet',
            name='apta',
            field=models.FloatField(blank=True, choices=[(1.46, 'tr\xe8s bas: 1.46'), (1.19, 'bas: 1.19'), (1.0, 'moyen: 1.00'), (0.86, '\xe9lev\xe9: 0.86'), (0.71, 'tr\xe8s \xe9lev\xe9: 0.71')], default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='aptp',
            field=models.FloatField(blank=True, choices=[(1.42, 'tr\xe8s bas: 1.42'), (1.17, 'bas: 1.17'), (1.0, 'moyen: 1.00'), (0.86, '\xe9lev\xe9: 0.86'), (0.7, 'tr\xe8s \xe9lev\xe9: 0.70')], default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='cplx',
            field=models.FloatField(blank=True, choices=[(0.7, 'tr\xe8s bas: 0.70'), (0.85, 'bas: 0.85'), (1.0, 'moyen: 1.00'), (1.15, '\xe9lev\xe9: 1.15'), (1.3, 'tr\xe8s \xe9lev\xe9: 1.30'), (1.65, 'tr\xe8s tr\xe8s \xe9lev\xe9: 1.65')], default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='csys',
            field=models.FloatField(blank=True, choices=[(0.87, 'bas: 0.87'), (1.0, 'moyen: 1.00'), (1.07, '\xe9lev\xe9: 1.07'), (1.15, 'tr\xe8s \xe9lev\xe9: 1.15')], default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='donn',
            field=models.FloatField(blank=True, choices=[(0.94, 'bas (0.94)'), (1.0, 'moyen (1.00)'), (1.08, '\xe9lev\xe9 (1.08)'), (1.16, 'tr\xe8s \xe9lev\xe9 (1.16)')], default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='dreq',
            field=models.FloatField(blank=True, choices=[(1.23, 'tr\xe8s bas: 1.23'), (1.08, 'bas: 1.08'), (1.0, 'moyen: 1.00'), (1.04, '\xe9lev\xe9: 1.04'), (1.1, 'tr\xe8s \xe9lev\xe9: 1.10')], default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='espa',
            field=models.FloatField(blank=True, choices=[(1.0, 'moyen: 1.00'), (1.06, '\xe9lev\xe9: 1.06'), (1.21, 'tr\xe8s \xe9lev\xe9: 1.21'), (1.56, 'tr\xe8s tr\xe8s \xe9lev\xe9: 1.56')], default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='expa',
            field=models.FloatField(blank=True, choices=[(1.29, 'tr\xe8s bas: 1.29'), (1.13, 'bas: 1.13'), (1.0, 'moyen: 1.00'), (0.91, '\xe9lev\xe9: 0.91'), (0.82, 'tr\xe8s \xe9lev\xe9: 0.82')], default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='expl',
            field=models.FloatField(blank=True, choices=[(1.14, 'tr\xe8s bas: 1.14'), (1.07, 'bas: 1.07'), (1.0, 'moyen: 1.00'), (0.95, '\xe9lev\xe9: 0.95')], default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='expv',
            field=models.FloatField(blank=True, choices=[(1.21, 'tr\xe8s bas: 1.21'), (1.1, 'bas: 1.10'), (1.0, 'moyen: 1.00'), (0.95, '\xe9lev\xe9: 0.95')], default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='fiab',
            field=models.FloatField(blank=True, choices=[(0.75, 'tr\xe8s bas: 0.75'), (0.88, 'bas: 0.88'), (1.0, 'moyen: 1.00'), (1.15, '\xe9lev\xe9: 1.15'), (1.4, 'tr\xe8s \xe9lev\xe9: 1.40')], default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='olog',
            field=models.FloatField(blank=True, choices=[(1.24, 'tr\xe8s bas: 1.24'), (1.1, 'bas: 1.10'), (1.0, 'moyen: 1.00'), (0.91, '\xe9lev\xe9: 0.91'), (0.83, 'tr\xe8s \xe9lev\xe9: 0.83')], default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='pmod',
            field=models.FloatField(blank=True, choices=[(1.24, 'tr\xe8s bas: 1.24'), (1.1, 'bas: 1.10'), (1.0, 'moyen: 1.00'), (0.91, '\xe9lev\xe9: 0.91'), (0.82, 'tr\xe8s \xe9lev\xe9: 0.82')], default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='temp',
            field=models.FloatField(blank=True, choices=[(1.0, 'moyen: 1.00'), (1.11, '\xe9lev\xe9: 1.11'), (1.3, 'tr\xe8s \xe9lev\xe9: 1.30'), (1.66, 'tr\xe8s tr\xe8s \xe9lev\xe9: 1.66')], default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='virt',
            field=models.FloatField(blank=True, choices=[(0.87, 'bas: 0.87'), (1.0, 'moyen: 1.00'), (1.15, '\xe9lev\xe9: 1.15'), (1.3, 'tr\xe8s \xe9lev\xe9: 1.30')], default=1.0, null=True),
        ),
    ]
